vietnamese_fruits = {
    'xoài': 'mango',
    'dưa hấu': 'watermelon',
    'táo': 'apple',
    'cam': 'orange',
    'chuối': 'banana',
    'đu đủ': 'papaya',
    'thơm': 'pineapple',
    'ổi': 'guava',
    'thanh long': 'dragon fruit',
    'nho': 'grape',
    'vải': 'lychee',
    'dâu tây': 'strawberry',
    'lê': 'pear',
    'ổi giòn': 'crispy guava',
    'sầu riêng': 'durian',
    'chôm chôm': 'rambutan',
    'bưởi': 'pomelo',
    'hồng': 'pink',
    'quýt': 'tangerine',
    'kiwi': 'kiwi'
    }

vietnamese_nouns = {
    'bàn': 'table',
    'ghế': 'chair',
    'tivi': 'television',
    'điện thoại': 'phone',
    'máy tính': 'computer',
    'đèn': 'lamp',
    'tủ lạnh': 'refrigerator',
    'đồng hồ': 'watch',
    'áo': 'shirt',
    'quần': 'pants',
    'giày': 'shoes',
    'túi': 'bag',
    'bát': 'bowl',
    'đũa': 'chopsticks',
    'nồi': 'pot',
    'xoong': 'pan',
    'bếp': 'stove',
    'quạt': 'fan',
    'thảm': 'carpet',
    'gối': 'pillow'
}

vietnamese_pronouns = {
    'tôi': 'I/me',
    'ta': 'I/me (informal)',
    'mình': 'I/me (formal)',
    'bạn': 'you',
    'anh': 'he/him (older brother)',
    'chị': 'she/her (older sister)',
    'em': 'he/she/they/them (younger sibling)',
    'ông': 'he/him (grandfather/older man)',
    'bà': 'she/her (grandmother/older woman)',
    'anh ấy': 'he/him',
    'chị ấy': 'she/her',
    'em ấy': 'he/she/they/them (younger person)',
    'chú': 'he/him (uncle)',
    'cô': 'she/her (aunt)',
    'ông ấy': 'he/him (old man)',
    'bà ấy': 'she/her (old woman)',
    'họ': 'they/them',
    'chúng tôi': 'we/us (inclusive)',
    'tôi và bạn': 'we/us (exclusive)',
    'chúng mình': 'we/us (informal)',
    'anh và em': 'he/him and she/her/they/them',
    'anh/chị/em': 'older/younger siblings',
    'các bạn': 'you all',
    'các anh': 'all of the older brothers/men',
    'các chị': 'all of the older sisters/women'
}


